name: CI

# Define the events that will trigger this workflow
on:
  push:
     branches:
       - main
     paths-ignore:
       - 'helm/**'
       - 'README.md'

jobs:
  # Job 1: Build and Test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.22.5
        uses: actions/setup-go@v2
        with:
          go-version: 1.22.5

      - name: Build the Go application
        run: go build -o go-web-app

      - name: Run tests
        run: go test ./...

  # Job 2: Code Quality Check
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.56.2

  # Job 3: Build and Push Docker Image
  push:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{ github.run_id }}

  # Job 4: Update Helm Chart with New Tag
  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update tag in Helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{ github.run_id }}"/' Helm/go-web-app-charts/values.yaml

      - name: Commit and push changes
        run: |
          git config --global user.email "nandhinigoud965@gmail.com"
          git config --global user.name "nandini965"
          git add Helm/go-web-app-charts/values.yaml
          git commit -m "Update tag in Helm chart"
          git push