name: CI Simple Test

on:
  push:
    branches:
      - main

jobs:
  simple-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Commit Test File
        run: |
          echo "Test commit" > test.txt
          git add test.txt
          git commit -m "Add test file"
          git push
